export const reviewContextAttestationActionContractFragment = Object.freeze({
  fragmentVersion: 1,
  boundedContext: "review_context_attestation",
  publishedEnums: Object.freeze([
    Object.freeze({
      typeName: "ReviewContextGatewayOpenResultStatus",
      values: Object.freeze(["opened", "idempotent", "denied", "conflict"]),
    }),
    Object.freeze({
      typeName: "ReviewContextGatewaySealResultStatus",
      values: Object.freeze(["accepted", "idempotent", "denied", "conflict"]),
    }),
    Object.freeze({
      typeName: "ReviewContextReplayCommitResultStatus",
      values: Object.freeze(["accepted", "idempotent", "denied", "conflict"]),
    }),
    Object.freeze({
      typeName: "ReviewContextReceiptReplayCommitResultStatus",
      values: Object.freeze(["accepted", "idempotent", "denied", "conflict"]),
    }),
  ]),
  operations: Object.freeze([
    Object.freeze({
      operationId: "review_context_gateway_open",
      requestTypeName: "ReviewContextGatewayOpenRequest",
      resultTypeName: "ReviewContextGatewayOpenResult",
      callerAuthority: "run_authorization_and_lease_capability",
      mutability: "command",
      naturalIdempotencyPreimage: Object.freeze([
        "attempt_id",
        "source_lease_id",
        "fencing_token",
        "source_execution_id",
        "source_work_slot_id",
        "source_review_revision_hash",
        "checkout_tree_oid",
        "gateway_policy_version",
        "gateway_binary_hash",
        "confinement_evidence_hash",
      ]),
      semanticRetryClass: "same_request",
      requestFields: Object.freeze([
        Object.freeze({ name: "attemptId", type: "identifier" }),
        Object.freeze({ name: "sourceLeaseId", type: "identifier" }),
        Object.freeze({ name: "fencingToken", type: "decimal" }),
        Object.freeze({ name: "sourceExecutionId", type: "identifier" }),
        Object.freeze({ name: "sourceWorkSlotId", type: "identifier" }),
        Object.freeze({ name: "sourceReviewRevisionHash", type: "hash" }),
        Object.freeze({ name: "checkoutTreeOid", type: "git_oid" }),
        Object.freeze({ name: "gatewayPolicyVersion", type: "identifier" }),
        Object.freeze({ name: "gatewayBinaryHash", type: "hash" }),
        Object.freeze({ name: "confinementEvidenceHash", type: "hash" }),
      ]),
      resultStatusEnum: "ReviewContextGatewayOpenResultStatus",
      resultFields: Object.freeze([
        Object.freeze({ name: "sessionId", type: "nullable_identifier" }),
        Object.freeze({
          name: "eventChainSeedHash",
          type: "nullable_hash",
        }),
        Object.freeze({
          name: "gatewaySessionSecret",
          type: "nullable_token",
        }),
        Object.freeze({ name: "sealCapability", type: "nullable_token" }),
        Object.freeze({ name: "expiresAt", type: "nullable_timestamp" }),
      ]),
    }),
    Object.freeze({
      operationId: "review_context_gateway_seal",
      requestTypeName: "ReviewContextGatewaySealRequest",
      resultTypeName: "ReviewContextGatewaySealResult",
      callerAuthority: "run_authorization_and_lease_capability",
      mutability: "command",
      naturalIdempotencyPreimage: Object.freeze([
        "session_id",
        "attempt_id",
        "source_lease_id",
        "fencing_token",
        "terminal_outcome_hash",
        "transcript_hash",
        "replay_material_hash",
      ]),
      semanticRetryClass: "same_request",
      requestFields: Object.freeze([
        Object.freeze({ name: "sessionId", type: "identifier" }),
        Object.freeze({ name: "sealCapability", type: "token" }),
        Object.freeze({ name: "attemptId", type: "identifier" }),
        Object.freeze({ name: "sourceLeaseId", type: "identifier" }),
        Object.freeze({ name: "fencingToken", type: "decimal" }),
        Object.freeze({ name: "providerSucceeded", type: "boolean" }),
        Object.freeze({ name: "schemaValidated", type: "boolean" }),
        Object.freeze({ name: "fullyConsumed", type: "boolean" }),
        Object.freeze({ name: "actualModel", type: "string" }),
        Object.freeze({ name: "terminalOutcomeHash", type: "hash" }),
        Object.freeze({
          name: "transcriptCanonicalJson",
          type: "canonical_json",
        }),
        Object.freeze({ name: "transcriptHash", type: "hash" }),
        Object.freeze({
          name: "replayMaterialCanonicalJson",
          type: "canonical_json",
        }),
        Object.freeze({ name: "replayMaterialHash", type: "hash" }),
      ]),
      resultStatusEnum: "ReviewContextGatewaySealResultStatus",
      resultFields: Object.freeze([
        Object.freeze({ name: "attestationId", type: "nullable_identifier" }),
        Object.freeze({ name: "attestationHash", type: "nullable_hash" }),
      ]),
    }),
    Object.freeze({
      operationId: "review_context_receipt_replay_commit",
      requestTypeName: "ReviewContextReceiptReplayCommitRequest",
      resultTypeName: "ReviewContextReceiptReplayCommitResult",
      callerAuthority: "run_authorization",
      mutability: "command",
      naturalIdempotencyPreimage: Object.freeze([
        "execution_id",
        "work_slot_id",
        "attestation_id",
        "source_operation_receipt_ids_hash",
        "target_review_revision_hash",
        "replay_result_hash",
      ]),
      semanticRetryClass: "same_request",
      requestFields: Object.freeze([
        Object.freeze({ name: "executionId", type: "identifier" }),
        Object.freeze({ name: "workSlotId", type: "identifier" }),
        Object.freeze({ name: "attestationId", type: "identifier" }),
        Object.freeze({ name: "attestationHash", type: "hash" }),
        Object.freeze({ name: "targetReviewRevisionHash", type: "hash" }),
        Object.freeze({ name: "targetCheckoutTreeOid", type: "git_oid" }),
        Object.freeze({ name: "replayCapability", type: "token" }),
        Object.freeze({
          name: "replayResultCanonicalJson",
          type: "canonical_json",
        }),
        Object.freeze({ name: "replayResultHash", type: "hash" }),
      ]),
      resultStatusEnum: "ReviewContextReceiptReplayCommitResultStatus",
      resultFields: Object.freeze([
        Object.freeze({ name: "replayProofId", type: "nullable_identifier" }),
        Object.freeze({ name: "replayProofHash", type: "nullable_hash" }),
      ]),
    }),
    Object.freeze({
      operationId: "review_context_replay_commit",
      requestTypeName: "ReviewContextReplayCommitRequest",
      resultTypeName: "ReviewContextReplayCommitResult",
      callerAuthority: "run_authorization",
      mutability: "command",
      naturalIdempotencyPreimage: Object.freeze([
        "execution_id",
        "work_slot_id",
        "attestation_id",
        "attestation_hash",
        "target_review_revision_hash",
        "target_checkout_tree_oid",
        "replay_result_hash",
      ]),
      semanticRetryClass: "same_request",
      requestFields: Object.freeze([
        Object.freeze({ name: "executionId", type: "identifier" }),
        Object.freeze({ name: "workSlotId", type: "identifier" }),
        Object.freeze({ name: "attestationId", type: "identifier" }),
        Object.freeze({ name: "attestationHash", type: "hash" }),
        Object.freeze({ name: "targetReviewRevisionHash", type: "hash" }),
        Object.freeze({ name: "targetCheckoutTreeOid", type: "git_oid" }),
        Object.freeze({ name: "replayCapability", type: "token" }),
        Object.freeze({
          name: "replayResultCanonicalJson",
          type: "canonical_json",
        }),
        Object.freeze({ name: "replayResultHash", type: "hash" }),
      ]),
      resultStatusEnum: "ReviewContextReplayCommitResultStatus",
      resultFields: Object.freeze([
        Object.freeze({ name: "replayProofId", type: "nullable_identifier" }),
        Object.freeze({ name: "replayProofHash", type: "nullable_hash" }),
        Object.freeze({
          name: "attachmentCapability",
          type: "nullable_token",
        }),
      ]),
    }),
  ]),
});
