/**
 * Canonical release-authority privilege policy.
 *
 * This is deliberately a data-only domain contract. PostgreSQL catalog names,
 * OIDs, aclitem parsing, and migration mechanics belong to adapters.
 */
export const releaseAuthorityDefaultAclPolicy = Object.freeze({
  creatingOwner: "authority_owner",
  scopes: Object.freeze(["global", "authority_schema"]),
  objectKinds: Object.freeze(["tables", "sequences", "routines", "types"]),
  grants: Object.freeze([]),
});

const controlRoutines = Object.freeze([
  "authorize_activation",
  "observe_state",
  "release_migration_begin",
  "release_migration_checkpoint",
  "release_migration_complete",
  "release_migration_fail",
  "release_provider_mutation_complete",
  "release_provider_mutation_consume",
  "release_provider_mutation_issue",
  "release_provider_mutation_recover",
  "release_provider_mutation_reconcile",
  "release_provider_mutation_validate_execution",
  "release_recovery_effect_claim",
  "release_recovery_effect_complete",
  "release_recovery_effect_consume",
  "release_recovery_effect_intend",
  "release_recovery_effect_reconcile",
  "release_recovery_effect_validate_execution",
  "release_rollout_activation_state",
  "release_rollout_append_receipt",
  "release_rollout_claim_transition",
  "release_rollout_compensation_checkpoint",
  "release_rollout_fence_target_switch",
  "release_rollout_finalize_activation",
  "release_rollout_mark_activation_uncertain",
  "release_rollout_reconcile",
  "release_rollout_reconciliation_context",
  "release_rollout_verify_final_authority",
  "release_runner_abandon_prepared",
  "release_runner_acquire_dispatch_permit",
  "release_runner_cleanup_observation",
  "release_runner_cleanup_witness",
  "release_runner_current",
  "release_runner_list_intents",
  "release_runner_list_open_jobs",
  "release_runner_mark_terminal",
  "release_runner_persist_identity",
  "release_runner_persist_job",
  "release_runner_persist_registration",
  "release_runner_prepare_effect",
  "release_runner_reconcile_effect",
  "release_runner_terminal_cleanup_fact",
  "release_schema_migration_manifest",
  "release_service_transition_activation_gate",
  "release_service_transition_append",
  "release_service_transition_begin",
  "release_service_transition_complete",
  "release_service_transition_contract",
  "release_service_transition_read",
  "release_source_freeze_complete",
  "release_source_freeze_prepare",
  "release_source_freeze_record",
]);

export const releaseAuthorityFinalAclPolicy = Object.freeze({
  owner: "authority_owner",
  schema: Object.freeze({
    name: "release_authority",
    ownerPrivileges: Object.freeze(["CREATE", "USAGE"]),
    usagePrivileges: Object.freeze(["USAGE"]),
    usageRoles: Object.freeze([
      "reviewrouter_provider_authority",
      "reviewrouter_release_control",
      "reviewrouter_release_witness",
    ]),
  }),
  relations: Object.freeze([
    "provider_authority_decision",
    "provider_mutation",
    "provider_resource_lease",
    "receipt",
    "recovery_effect",
    "release_migration_evidence",
    "rollout",
    "runner_intent",
    "runner_job",
    "schema_migration",
    "service_transition",
    "service_transition_checkpoint",
    "source_freeze_completion",
    "source_freeze_observation",
    "target_generation_claim",
  ]),
  sequences: Object.freeze(["source_freeze_observation_observation_id_seq"]),
  relationOwnerPrivileges: Object.freeze([
    "DELETE",
    "INSERT",
    "MAINTAIN",
    "REFERENCES",
    "SELECT",
    "TRIGGER",
    "TRUNCATE",
    "UPDATE",
  ]),
  sequenceOwnerPrivileges: Object.freeze(["USAGE"]),
  routineOwnerPrivileges: Object.freeze(["EXECUTE"]),
  routineExecutePrivileges: Object.freeze(["EXECUTE"]),
  typeOwnerPrivileges: Object.freeze(["USAGE"]),
  routines: Object.freeze([
    "authorize_activation",
    "observe_state",
    "release_canonical_json",
    "release_migration_begin",
    "release_migration_begin_v13",
    "release_migration_checkpoint",
    "release_migration_checkpoint_v13",
    "release_migration_complete",
    "release_migration_complete_v13",
    "release_migration_fail",
    "release_migration_fail_v13",
    "release_compensation_effects_are_safe",
    "release_compensation_receipt_effect_gate",
    "release_compensation_source_recovery_gate",
    "release_late_job_recovery_effect_gate",
    "release_provider_authority_decide",
    "release_provider_mutation_complete",
    "release_provider_mutation_authority_is_current",
    "release_provider_mutation_consume",
    "release_provider_mutation_finish",
    "release_provider_mutation_issue",
    "release_provider_mutation_recover",
    "release_provider_mutation_permit",
    "release_provider_mutation_receipt",
    "release_provider_mutation_outcome",
    "release_provider_mutation_reconcile",
    "release_provider_mutation_validate_execution",
    "release_recovery_checkpoint_permit_gate",
    "release_recovery_effect_claim",
    "release_recovery_effect_complete",
    "release_recovery_effect_consume",
    "release_recovery_effect_intend",
    "release_recovery_effect_observation_is_valid",
    "release_recovery_effect_reconcile",
    "release_recovery_effect_snapshot",
    "release_recovery_effect_validate_execution",
    "release_rollout_activation_state",
    "release_rollout_append_receipt",
    "release_rollout_claim",
    "release_rollout_claim_transition",
    "release_rollout_compensation_checkpoint",
    "release_rollout_fence_target_switch",
    "release_rollout_finalize_activation",
    "release_rollout_mark_activation_uncertain",
    "release_rollout_receipt_immutable",
    "release_rollout_reconcile",
    "release_rollout_reconciliation_context",
    "release_rollout_verify_final_authority",
    "release_runner_abandon_prepared",
    "release_runner_acquire_dispatch_permit",
    "release_runner_claim_provider_creation",
    "release_runner_cleanup_observation",
    "release_runner_cleanup_observation_seed",
    "release_runner_cleanup_witness",
    "release_runner_compensation_gate",
    "release_runner_current",
    "release_runner_effect_snapshot",
    "release_runner_job_cleanup_proven",
    "release_runner_list_intents",
    "release_runner_list_open_jobs",
    "release_runner_mark_terminal",
    "release_runner_persist_cleanup_witness",
    "release_runner_persist_identity",
    "release_runner_persist_intent",
    "release_runner_persist_job",
    "release_runner_persist_registration",
    "release_runner_prepare_effect",
    "release_runner_reconcile_effect",
    "release_runner_record_intent_outcome",
    "release_runner_terminal_cleanup_fact",
    "release_runner_terminal_effect",
    "release_schema_migration_manifest",
    "release_service_transition_activation_gate",
    "release_service_transition_append",
    "release_service_transition_begin",
    "release_service_transition_complete",
    "release_service_transition_contract",
    "release_service_transition_immutable",
    "release_service_transition_read",
    "release_source_freeze_complete",
    "release_source_freeze_immutable",
    "release_source_freeze_inventory_canonical",
    "release_source_freeze_prepare",
    "release_source_freeze_record",
    "release_source_resume_is_rollout_owned",
  ]),
  routineExecuteRoles: Object.freeze({
    reviewrouter_release_control: controlRoutines,
    reviewrouter_provider_authority: Object.freeze([
      "release_provider_authority_decide",
      "release_schema_migration_manifest",
    ]),
    reviewrouter_release_witness: Object.freeze([
      "release_runner_cleanup_observation_seed",
      "release_runner_persist_cleanup_witness",
      "release_schema_migration_manifest",
    ]),
  }),
  // The NOLOGIN broker is the sole role allowed to grant a short-lived
  // migration session the NOLOGIN authority owner. The lease membership is
  // consumed and revoked inside one database connection.
  roleMemberships: Object.freeze([
    Object.freeze({
      grantedRole: "reviewrouter_authority_owner",
      memberRole: "reviewrouter_migration_broker",
      grantorRole: "provisioned_grantor",
      admin: true,
      inherit: false,
      set: false,
    }),
  ]),
  // Only the explicitly declared enum is privilege-bearing. PostgreSQL's
  // generated table row/array types are still owner-checked by the adapter.
  declaredTypes: Object.freeze(["aggregate_state"]),
  publicPrivileges: Object.freeze([]),
  grantOptions: Object.freeze([]),
});
