export {
  ContextCriticDecision,
  ContextOperationFailureClass,
  ContextOperationOutcomeKind,
  InvestigationObligationKind,
  InvestigationObligationState,
  ReviewInvestigationAbortReason,
  ReviewInvestigationConclusion,
  ReviewInvestigationFeatureFlag,
  ReviewInvestigationNextActionKind,
  ReviewInvestigationRuntimeProfile,
  ReviewInvestigationState,
  ReviewInvestigationTurnPurpose,
} from "../domain/review-investigation-types";

import {
  ReviewInvestigationAbortReason,
  ReviewInvestigationConclusion,
  ReviewInvestigationNextActionKind,
  ReviewInvestigationRuntimeProfile,
  ReviewInvestigationState,
} from "../domain/review-investigation-types";

const commonResultFields = Object.freeze([
  Object.freeze({ name: "investigationId", type: "nullable_identifier" }),
  Object.freeze({ name: "investigationVersion", type: "nullable_decimal" }),
  Object.freeze({
    name: "investigationState",
    type: "nullable_enum",
    enumTypeName: "ReviewInvestigationPublishedState",
  }),
  Object.freeze({ name: "dossierDigest", type: "nullable_hash" }),
  Object.freeze({
    name: "nextAction",
    type: "nullable_enum",
    enumTypeName: "ReviewInvestigationNextAction",
  }),
  Object.freeze({
    name: "investigationCanonicalJson",
    type: "nullable_canonical_json",
  }),
  Object.freeze({ name: "certificateId", type: "nullable_identifier" }),
  Object.freeze({ name: "certificateHash", type: "nullable_hash" }),
  Object.freeze({ name: "terminalProviderKind", type: "nullable_string" }),
  Object.freeze({ name: "terminalActualModel", type: "nullable_string" }),
  Object.freeze({
    name: "terminalObservationCanonicalJson",
    type: "nullable_canonical_json",
  }),
  Object.freeze({ name: "terminalOutcomeHash", type: "nullable_hash" }),
  Object.freeze({
    name: "investigationConclusion",
    type: "nullable_enum",
    enumTypeName: "ReviewInvestigationPublishedConclusion",
  }),
]);

export const reviewInvestigationsActionContractFragment = Object.freeze({
  fragmentVersion: 1,
  boundedContext: "review_investigations",
  publishedEnums: Object.freeze([
    Object.freeze({
      typeName: "ReviewInvestigationOpenResultStatus",
      values: Object.freeze(["opened", "restored", "rejected", "conflict"]),
    }),
    Object.freeze({
      typeName: "ReviewInvestigationRestoreResultStatus",
      values: Object.freeze(["found", "missing", "not_restorable"]),
    }),
    Object.freeze({
      typeName: "ReviewInvestigationMutationResultStatus",
      values: Object.freeze([
        "applied",
        "restored",
        "parked",
        "rejected",
        "conflict",
        "missing",
      ]),
    }),
    Object.freeze({
      typeName: "ReviewInvestigationNextAction",
      values: Object.freeze(Object.values(ReviewInvestigationNextActionKind)),
    }),
    Object.freeze({
      typeName: "ReviewInvestigationPublishedState",
      values: Object.freeze(Object.values(ReviewInvestigationState)),
    }),
    Object.freeze({
      typeName: "ReviewInvestigationPublishedRuntimeProfile",
      values: Object.freeze(Object.values(ReviewInvestigationRuntimeProfile)),
    }),
    Object.freeze({
      typeName: "ReviewInvestigationPublishedAbortReason",
      values: Object.freeze(Object.values(ReviewInvestigationAbortReason)),
    }),
    Object.freeze({
      typeName: "ReviewInvestigationPublishedConclusion",
      values: Object.freeze(Object.values(ReviewInvestigationConclusion)),
    }),
  ]),
  operations: Object.freeze([
    Object.freeze({
      operationId: "review_investigation_open",
      requestTypeName: "ReviewInvestigationOpenRequest",
      resultTypeName: "ReviewInvestigationOpenResult",
      callerAuthority: "run_authorization",
      mutability: "command",
      naturalIdempotencyPreimage: Object.freeze([
        "execution_id",
        "work_slot_id",
        "review_revision_hash",
        "stable_review_unit_key",
        "provider_vote_lane_id",
        "coverage_contract_hash",
        "runtime_profile_version",
      ]),
      semanticRetryClass: "same_request",
      requestFields: Object.freeze([
        Object.freeze({ name: "authorizationId", type: "identifier" }),
        Object.freeze({ name: "executionId", type: "identifier" }),
        Object.freeze({ name: "workSlotId", type: "identifier" }),
        Object.freeze({ name: "reviewRevisionHash", type: "hash" }),
        Object.freeze({ name: "stableReviewUnitKey", type: "identifier" }),
        Object.freeze({ name: "providerVoteLaneId", type: "identifier" }),
        Object.freeze({ name: "providerStrategyId", type: "identifier" }),
        Object.freeze({
          name: "runtimeProfile",
          type: "enum",
          enumTypeName: "ReviewInvestigationPublishedRuntimeProfile",
        }),
        Object.freeze({
          name: "coverageContractCanonicalJson",
          type: "canonical_json",
        }),
        Object.freeze({ name: "coverageContractHash", type: "hash" }),
        Object.freeze({
          name: "investigationPolicyCanonicalJson",
          type: "canonical_json",
        }),
        Object.freeze({ name: "investigationPolicyHash", type: "hash" }),
        Object.freeze({
          name: "seedObligationsCanonicalJson",
          type: "canonical_json",
        }),
        Object.freeze({ name: "seedObligationsHash", type: "hash" }),
        Object.freeze({
          name: "initialReceiptsCanonicalJson",
          type: "canonical_json",
        }),
        Object.freeze({ name: "initialReceiptsHash", type: "hash" }),
      ]),
      resultStatusEnum: "ReviewInvestigationOpenResultStatus",
      resultFields: commonResultFields,
    }),
    Object.freeze({
      operationId: "review_investigation_restore",
      requestTypeName: "ReviewInvestigationRestoreRequest",
      resultTypeName: "ReviewInvestigationRestoreResult",
      callerAuthority: "run_authorization",
      mutability: "read",
      naturalIdempotencyPreimage: Object.freeze([
        "authorization_id",
        "investigation_id",
        "review_revision_hash",
      ]),
      semanticRetryClass: "read_only",
      requestFields: Object.freeze([
        Object.freeze({ name: "authorizationId", type: "identifier" }),
        Object.freeze({ name: "investigationId", type: "identifier" }),
        Object.freeze({ name: "reviewRevisionHash", type: "hash" }),
      ]),
      resultStatusEnum: "ReviewInvestigationRestoreResultStatus",
      resultFields: commonResultFields,
    }),
    Object.freeze({
      operationId: "review_investigation_turn_plan",
      requestTypeName: "ReviewInvestigationTurnPlanRequest",
      resultTypeName: "ReviewInvestigationTurnPlanResult",
      callerAuthority: "run_authorization",
      mutability: "command",
      naturalIdempotencyPreimage: Object.freeze([
        "investigation_id",
        "expected_version",
        "dossier_digest",
        "turn_budget_hash",
      ]),
      semanticRetryClass: "same_request",
      requestFields: Object.freeze([
        Object.freeze({ name: "investigationId", type: "identifier" }),
        Object.freeze({ name: "expectedVersion", type: "decimal" }),
        Object.freeze({ name: "dossierDigest", type: "hash" }),
        Object.freeze({ name: "leaseDurationMs", type: "positive_integer" }),
        Object.freeze({
          name: "maxObligationsForTurn",
          type: "positive_integer",
        }),
        Object.freeze({ name: "turnBudgetHash", type: "hash" }),
      ]),
      resultStatusEnum: "ReviewInvestigationMutationResultStatus",
      resultFields: Object.freeze([
        ...commonResultFields,
        Object.freeze({ name: "turnId", type: "nullable_identifier" }),
        Object.freeze({ name: "turnCapability", type: "nullable_token" }),
        Object.freeze({ name: "turnExpiresAt", type: "nullable_timestamp" }),
        Object.freeze({
          name: "turnBriefCanonicalJson",
          type: "canonical_json",
        }),
        Object.freeze({ name: "turnBriefHash", type: "hash" }),
      ]),
    }),
    Object.freeze({
      operationId: "review_investigation_turn_commit",
      requestTypeName: "ReviewInvestigationTurnCommitRequest",
      resultTypeName: "ReviewInvestigationTurnCommitResult",
      callerAuthority: "run_authorization_and_lease_capability",
      mutability: "command",
      naturalIdempotencyPreimage: Object.freeze([
        "investigation_id",
        "expected_version",
        "turn_id",
        "source_lease_id",
        "fencing_token",
        "turn_observation_hash",
        "accepted_attestation_hash",
      ]),
      semanticRetryClass: "same_request",
      requestFields: Object.freeze([
        Object.freeze({ name: "investigationId", type: "identifier" }),
        Object.freeze({ name: "expectedVersion", type: "decimal" }),
        Object.freeze({ name: "turnId", type: "identifier" }),
        Object.freeze({ name: "turnCapability", type: "token" }),
        Object.freeze({ name: "sourceLeaseId", type: "identifier" }),
        Object.freeze({ name: "fencingToken", type: "decimal" }),
        Object.freeze({ name: "acceptedAttestationId", type: "identifier" }),
        Object.freeze({ name: "acceptedAttestationHash", type: "hash" }),
        Object.freeze({
          name: "turnObservationCanonicalJson",
          type: "canonical_json",
        }),
        Object.freeze({ name: "turnObservationHash", type: "hash" }),
      ]),
      resultStatusEnum: "ReviewInvestigationMutationResultStatus",
      resultFields: commonResultFields,
    }),
    Object.freeze({
      operationId: "review_investigation_turn_abort",
      requestTypeName: "ReviewInvestigationTurnAbortRequest",
      resultTypeName: "ReviewInvestigationTurnAbortResult",
      callerAuthority: "run_authorization_and_lease_capability",
      mutability: "command",
      naturalIdempotencyPreimage: Object.freeze([
        "investigation_id",
        "expected_version",
        "turn_id",
        "source_lease_id",
        "fencing_token",
        "abort_reason",
      ]),
      semanticRetryClass: "same_request",
      requestFields: Object.freeze([
        Object.freeze({ name: "investigationId", type: "identifier" }),
        Object.freeze({ name: "expectedVersion", type: "decimal" }),
        Object.freeze({ name: "turnId", type: "identifier" }),
        Object.freeze({ name: "turnCapability", type: "token" }),
        Object.freeze({ name: "sourceLeaseId", type: "identifier" }),
        Object.freeze({ name: "fencingToken", type: "decimal" }),
        Object.freeze({
          name: "abortReason",
          type: "enum",
          enumTypeName: "ReviewInvestigationPublishedAbortReason",
        }),
        Object.freeze({ name: "nextEligibleAt", type: "nullable_timestamp" }),
      ]),
      resultStatusEnum: "ReviewInvestigationMutationResultStatus",
      resultFields: commonResultFields,
    }),
    Object.freeze({
      operationId: "review_investigation_conclude",
      requestTypeName: "ReviewInvestigationConcludeRequest",
      resultTypeName: "ReviewInvestigationConcludeResult",
      callerAuthority: "run_authorization",
      mutability: "command",
      naturalIdempotencyPreimage: Object.freeze([
        "investigation_id",
        "expected_version",
        "dossier_digest",
        "certificate_ttl_ms",
      ]),
      semanticRetryClass: "same_request",
      requestFields: Object.freeze([
        Object.freeze({ name: "investigationId", type: "identifier" }),
        Object.freeze({ name: "expectedVersion", type: "decimal" }),
        Object.freeze({ name: "dossierDigest", type: "hash" }),
        Object.freeze({ name: "certificateTtlMs", type: "positive_integer" }),
      ]),
      resultStatusEnum: "ReviewInvestigationMutationResultStatus",
      resultFields: Object.freeze([
        ...commonResultFields,
      ]),
    }),
  ]),
});
